/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uuu.totalbuy.gui;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uuu.totalbuy.domain.BloodType;
import uuu.totalbuy.domain.Customer;
import uuu.totalbuy.domain.TotalBuyException;
import uuu.totalbuy.domain.VIP;
import uuu.totalbuy.model.CustomerService;

/**
 *
 * @author PattyTai
 */
public class CustomerFrame extends javax.swing.JFrame {

    private CustomerService service = new CustomerService();

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        getAllButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customersTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        birthdayField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bloodTypeCombo = new javax.swing.JComboBox<>();
        marriedCheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        vipCheck = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        discountSpinner = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        getButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        getAllButton.setText("查詢全部客戶");
        getAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllButtonActionPerformed(evt);
            }
        });
        jPanel1.add(getAllButton, java.awt.BorderLayout.PAGE_START);

        customersTable1.setAutoCreateRowSorter(true);
        customersTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Gender", "Email", "Birthday", "Phone", "Address", "Married", "BloodType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customersTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("客戶清單", jPanel1);

        jPanel2.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel1.setText("身分證號");

        try {
            idField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        idField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel2.setText("姓名");

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel3.setText("性別");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        maleRadioButton.setText("男");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        femaleRadioButton.setText("女");

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel4.setText("密碼");

        passwordField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        emailField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel6.setText("生日");

        birthdayField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        birthdayField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel7.setText("電話");

        phoneField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel8.setText("地址");

        addressField.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel9.setText("血型");

        bloodTypeCombo.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        bloodTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(uuu.totalbuy.domain.BloodType.values()));

        marriedCheck.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        marriedCheck.setText("已婚");

        jLabel10.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel10.setText("會員等級");

        vipCheck.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        vipCheck.setText("VIP");
        vipCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipCheckActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel11.setText("折扣");

        discountSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));

        jLabel12.setFont(new java.awt.Font("新細明體", 0, 14)); // NOI18N
        jLabel12.setText("%");

        insertButton.setText("新增");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("修改");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("刪除");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        getButton.setText("查詢");
        getButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(birthdayField)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maleRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(passwordField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bloodTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marriedCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vipCheck)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bloodTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marriedCheck)
                    .addComponent(jLabel10)
                    .addComponent(vipCheck)
                    .addComponent(jLabel11)
                    .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(getButton))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("客戶明細", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("getButtonActionPerformed");
        try {
            String id = (String) idField.getValue();
            if (id == null) {
                throw new TotalBuyException("查詢前請輸入id!");
            }
            Customer c = service.get(id);
            if (c != null) {
                //將c顯示在各controls中
                showCustomer(c);
            } else {
                JOptionPane.showMessageDialog(this, "查無客戶: " + id);
                showCustomer(new Customer());
            }
        } catch (Exception ex) {
            //將ex顯示在訊息對話窗中
            showException(ex);
        }
    }//GEN-LAST:event_getButtonActionPerformed

    private void getAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllButtonActionPerformed
        // TODO add your handling code here:
        try {
            List<Customer> list = service.getAll();

            //將list顯示在customersTable中
            DefaultTableModel model = (DefaultTableModel) customersTable1.getModel();
            model.setRowCount(0);
            if (list != null && list.size() > 0) {
                for (Customer c : list) {
                    model.addRow(
                            new Object[]{
                                c.getId(),
                                c.getName(),
                                String.valueOf(c.getGender()),
                                c.getEmail(),
                                c.getBirthday(),
                                c.getPhone(),
                                c.getAddress(),
                                c.isMarried(),
                                c.getBloodType()
                            }
                    );
                }
            }
        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_getAllButtonActionPerformed

    private void vipCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipCheckActionPerformed
        // TODO add your handling code here:
        System.out.println("vipCheckActionPerformed");

        discountSpinner.setEnabled(vipCheck.isSelected());
    }//GEN-LAST:event_vipCheckActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:   
        try {
            Customer c = getCustomer();
            service.register(c);
        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try {
            Customer c = getCustomer();
            service.update(c);
        } catch (Exception ex) {
            showException(ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:        
        
        try {            
            Customer c = getCustomer();
            if(c!=null){
                int rtn = JOptionPane.showConfirmDialog(this, "確定刪除嗎?");
                if(rtn==JOptionPane.OK_OPTION){
                    service.delete(c);
                    showCustomer(new Customer());
                }
            }
        } catch (Exception ex) {
            showException(ex);
        }        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private Customer getCustomer() throws TotalBuyException {
        Customer c = null;
        if (vipCheck.isSelected()) {
            c = new VIP();
        } else {
            c = new Customer();
        }
        try {
            c.setId((String) idField.getValue());
            c.setName(nameField.getText());
            c.setPassword(String.valueOf(passwordField.getPassword()));
            c.setGender(femaleRadioButton.isSelected() ? Customer.FEMALE : Customer.MALE);
            c.setEmail(emailField.getText());
            c.setBirthday((Date) birthdayField.getValue());
            c.setAddress(addressField.getText());
            c.setPhone(phoneField.getText());
            c.setMarried(marriedCheck.isSelected());
            c.setBloodType((BloodType) bloodTypeCombo.getSelectedItem());
            if (c instanceof VIP) {
                Number n = (Number) discountSpinner.getValue();
                ((VIP) c).setDiscount(n.intValue());
            }
        } catch (TotalBuyException ex) {
            throw ex;
        }
        return c;
    }

    private void showCustomer(Customer c) {
        System.out.println("查詢完成: " + c);
        idField.setValue(c.getId());
        nameField.setText(c.getName());
        maleRadioButton.setSelected(c.getGender() == Customer.MALE);
        femaleRadioButton.setSelected(c.getGender() == Customer.FEMALE);
        passwordField.setText(c.getPassword());
        emailField.setText(c.getEmail());

        birthdayField.setValue(c.getBirthday());
        phoneField.setText(c.getPhone());
        addressField.setText(c.getAddress());
        bloodTypeCombo.setSelectedItem(c.getBloodType());
        marriedCheck.setSelected(c.isMarried());

        vipCheck.setSelected(c instanceof VIP);
        if (c instanceof VIP) {
            discountSpinner.setValue(((VIP) c).getDiscount());
        } else {
            discountSpinner.setValue(0);
            discountSpinner.setEnabled(false);
        }
    }

    private void showException(Exception ex) {
        JOptionPane.showMessageDialog(this,
                ex instanceof TotalBuyException ? ex.getMessage() : ex.toString(), "系統發生錯誤", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JFormattedTextField birthdayField;
    private javax.swing.JComboBox<String> bloodTypeCombo;
    private javax.swing.JTable customersTable1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JSpinner discountSpinner;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JButton getAllButton;
    private javax.swing.JButton getButton;
    private javax.swing.JFormattedTextField idField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JCheckBox marriedCheck;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton updateButton;
    private javax.swing.JCheckBox vipCheck;
    // End of variables declaration//GEN-END:variables
}
